# These are supported funding model platforms

# github: [yyx990803, posva]
patreon: username
open_collective: username
ko_fi: username
tidelift: npm/babel
community_bridge: cloud-foundry
liberapay: username
issuehunt: username
otechie: username
custom: ['link1', 'link2']
